config/routes.rb
Rails.application.routes.draw do
  # First Page
  root "sessions#welcome"
  # Younger than 21
  get "/bye" => "sessions#bye"
  # Sign Out
  delete "/signout" => "sessions#destroy"
  # Sign Up
  get "/signup" => "users#new"
  # Sign In
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create"
  #Facebook SignIn
  get '/auth/facebook/callback' => 'sessions#oauth_login'
  #Number of Ingredients
  get "/cocktails/i" => "cocktails#i"
  post "/cocktails/i" => "cocktails#i"
  #Nested 'Cocktails#new'
  get "/cocktails/i/new" => "cocktails#new"

  resources :users

  resources :users do
    resources :cocktails, only: [:index] 
  end

  resources :cocktails, :except => [:new] do
    collection do
      get :sorted_abc
      get :sorted_zyx
    end
    resources :cocktail_ingredients, only: [:index, :new, :create, :destroy]
  end

end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    before_save {self.name.upcase!}
    validates :name, :instructions, presence: true
    belongs_to :user
    has_many :cocktail_ingredients
    has_many :ingredients, through: :cocktail_ingredients
    accepts_nested_attributes_for :cocktail_ingredients, allow_destroy: true

    scope :sorted_abc, -> { order('name') }
    scope :sorted_zyx, -> { order('name DESC') }
    scope :by_ingredient, -> (i){ joins(:ingredients).where("ingredients.name = ?", i) }

    def self.search(name)
        where(['name LIKE ?', "%#{name}%"])
    end

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    before_action :find_cocktail, only: [:show, :new, :edit, :update, :destroy]

    def index
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @cocktails = @user.cocktails
        else
            @error = "User doesn't exist" if params[:user_id]
            @cocktails = Cocktail.all
        end
        @cocktails = @cocktails.search(params[:name]) if params[:name] && !params[:name].empty?
        @cocktails = @cocktails.by_ingredient(params[:i]) if params[:i] && !params[:i].empty?
    end
      
    def show
        delete_empty
        redirect_to cocktails_path if !@cocktail
    end

    def i
        if logged_in? 
            if params[:i]
                @@i = params[:i][:i].to_i
                if @@i == 0
                    flash[:message] = "Please enter a number greater than 0!"
                    render 'i'
                else
                    redirect_to cocktails_i_new_path
                end
            else
                render 'i'
            end
        else
            flash[:message] = "You need an account to create a cocktail!"
            redirect_to cocktails_path
        end
    end

    def new
        if logged_in? 
            @cocktail = current_user.cocktails.new
            @@i.times do
                @cocktail.cocktail_ingredients.build.build_ingredient
            end
        else
            flash[:message] = "You need an account to create a cocktail!"
            redirect_to cocktails_path
        end
    end
      
    def create
        @cocktail = current_user.cocktails.new(cocktail_params)
        prepare_cocktail
        if @cocktail.save
            flash[:message] = "Cocktail Has Been Cteated Sucessfully!"
            redirect_to cocktail_path(@cocktail)
        else
            render 'new'
        end
    end
      
    def edit
        if !@cocktail || @cocktail.user != current_user				
            flash[:message]= "You can't edit this cocktail!"
            redirect_to cocktails_path
        end			
    end
      
    def update
        if !@cocktail || @cocktail.user != current_user				
            flash[:message]= "You can't edit this cocktail!"
            redirect_to cocktails_path
        else
            @cocktail.attributes = cocktail_params
            prepare_cocktail
            if @cocktail.save
                redirect_to cocktail_path(@cocktail)
                flash[:message] = "Cocktail Has Been Updated Sucessfully!"
            else
                render 'edit'
            end
        end
    end
      
    def destroy
        if !@cocktail || @cocktail.user != current_user				
            flash[:message]= "You can't delete this cocktail!"
            redirect_to cocktails_path
        else
            @cocktail.destroy
            flash[:message] = "Cocktail Has Been Deleted Succesfully!"
            redirect_to cocktails_path
        end
    end
    
    def sorted_abc
        @cocktails = Cocktail.all.sorted_abc
        render :index
    end

    def sorted_zyx
        @cocktails = Cocktail.all.sorted_zyx
        render :index
    end
      
    private

    def find_cocktail
        @cocktail = Cocktail.find_by_id(params[:id])
    end

    def cocktail_params
        params.require(:cocktail).permit(
            :name,
            :description,
            :instructions,
            :cocktail_ingredients_attributes => [
                :id,
                :quantity,
                :unit,
                :ingredient_attributes => [
                    :name
                ]
            ]
        )
    end

    def prepare_cocktail
        @cocktail.cocktail_ingredients.each do |cocktail_ingredient|
            if ingredient = Ingredient.where('LOWER(name) = ?', cocktail_ingredient.ingredient.name.downcase).first
                cocktail_ingredient.ingredient_id = cocktail_ingredient.ingredient.id = ingredient.id 
            end
        end
    end

    def delete_empty
        @cocktail = Cocktail.find_by_id(params[:id])
        @cocktail.ingredients.each do |i|
            if i.name == ""
                @item = @cocktail.cocktail_ingredients.find_by(ingredient_id: i)
                @item.delete
            end
        end
    end

end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_form.html.erb
<%= form_for @cocktail do |f| %>
    <div class="cocktail_name"> <%= f.label :name %> <%= f.text_field :name, :size=>"72" %> </div><br>
    <div class="cocktail_description"> <%= f.label :description %> <%= f.text_field :description, :size=>"68" %> </div><br>
    <div class="cocktails_ingredients"><%= f.label "Ingredients:" %><br><br>
        <%= f.fields_for :cocktail_ingredients do |ff| %>
            <div class="ingredient_fields">
                <%= ff.fields_for :ingredient do |fff| %>
                    <%= fff.label :name %>
                    <%= fff.text_field :name %>
                <% end %>
            <%= ff.label :quantity %> <%= ff.text_field :quantity %>
            <%= ff.select :unit, options_for_select(CocktailIngredient::UNITS, :selected => ff.object.unit) %> </div><br>
        <% end %>
    </div> <br>
    <div class="cocktail_instructions"> <%= f.label :instructions %> <%= f.text_field :instructions, :size=>"68" %> </div> <br>
  <%= f.submit "Submit" %>
<% end %> 

app/views/cocktails/_search.html.erb
<% unless params[:user_id] %>

<div>
    <div style="float: left;">
        <%= form_tag("/cocktails", method: "get", :class => "form") do %>
            Search by Cocktail Name: 
            <%= text_field_tag :name, params[:name] %>
            <button type=submit_tag >Search</button>
        <% end %>
    </div>
    <div style="float: left;">
        <%= form_tag("/cocktails", method: "get", :class => "form") do %>
            | or search by Ingredient Name: 
            <%= text_field_tag :i, params[:i] %>
            <button type=submit_tag >Search</button>
        <% end %>
    </div>
    <div style="float: right;">
        Order Names by: <%= link_to "ABC", sorted_abc_cocktails_path %> | <%= link_to "ZYX", sorted_zyx_cocktails_path %>
    </div>
</div>
<br><br>

<% end %>

app/views/cocktails/edit.html.erb
<%= render 'layouts/styling' %>
<br>
<%= render partial: 'layouts/errors', locals: {object: @cocktail}  %>
<br>
<fieldset class="cocktail", align="center"><br>
    <legend>Edit Cocktail:</h2></legend>
    <%= render 'form' %>
</fieldset>

app/views/cocktails/i.html.erb
<%= render 'layouts/styling' %>
<br>
<fieldset class="cocktail", align="center"><br>
    <legend>Ingredients:</h2></legend>

    <p>How many ingredients are there in a new Cocktail?</p><br>
        <%= form_for :i do |f| %>
            <%= f.text_field :i, :size=>"34" %><br><br>
        <%= f.submit "Submit" %>
        <% end %>

</fieldset>

app/views/cocktails/index.html.erb
<%= render 'search' %>
<% if @cocktails.size == 0 %>
    <h3> There is no Cocktails yet. Please create a new one! </h3> 
<% else %>
    <% @cocktails.each_slice(3) do |cocktail| %>
        <% cocktail.each do |i|%>
            <div align="center" class="float-left"><%= link_to i.name, cocktail_path(i) %></div>
        <%end%>
    <% end %>
<% end %>

app/views/cocktails/new.html.erb
<%= render 'layouts/styling' %>
<br>
<%= render partial: 'layouts/errors', locals: {object: @cocktail}  %>
<br>
<fieldset class="cocktail", align="center"><br>
    <legend>New Cocktail:</h2></legend>
    <%= render 'form' %>
</fieldset>

app/views/cocktails/show.html.erb
<%= render 'layouts/styling' %>
<br>
<%= render partial: 'layouts/errors', locals: {object: @user}  %>
<br>
<fieldset class="cocktail", align="center"><br>
    <legend>Cocktail:</h2></legend>
    <div class="cocktail_name"><h2><%= @cocktail.name %></h2><p><%= "by " + @cocktail.user.name %></p></div><br>
    <div class="cocktail_description"><p><%= @cocktail.description %></p></div><br>
    <div class="cocktails_ingredients"><%= "Ingredients:" %><br><br>
        <% @cocktail.cocktail_ingredients.each do |cocktail_ingredient| %>
            <div class="ingredient_fields">
                <%= form_tag(cocktail_cocktail_ingredient_path(@cocktail, cocktail_ingredient), method:"delete") do %>
                    <li><%= cocktail_ingredient.ingredient.name %> <%= cocktail_ingredient.quantity %> <%= cocktail_ingredient.unit %>
                        <% if logged_in? && @cocktail.user == current_user %>
                            <button type=submit_tag >x</button>
                        <% end %>
                <% end %>
            </li>
            </div><br>
        <% end %>
        <% if logged_in? && @cocktail.user == current_user %>
            <%= link_to "Add a New Ingredient", new_cocktail_cocktail_ingredient_path(@cocktail) %>
        <% end %>    
    </div> <br>
    <div class="cocktail_instructions"> <%= "Instructions:" %> <%= @cocktail.instructions %> </div> <br>

<% if logged_in? && @cocktail.user == current_user %>
    <div>
        <%= form_tag(edit_cocktail_path, method:"get") do %>
            <%= button_tag "Edit" %>
        <% end %>
    </div>
    <div>
        <%= form_tag(cocktail_path, method:"delete", confirm: "Are you sure?") do %>
            <%= button_tag "Delete" %>
        <% end %>
    </div>
<% end %>

</fieldset>