config/routes.rb
Rails.application.routes.draw do
  # First Page
  root "sessions#welcome"
  # Younger than 21
  get "/bye" => "sessions#bye"
  # Sign Out
  delete "/signout" => "sessions#destroy"
  # Sign Up
  get "/signup" => "users#new"
  # Sign In
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create"
  #Facebook SignIn
  get '/auth/facebook/callback' => 'sessions#oauth_login'
  #Number of Ingredients
  get "/cocktails/i" => "cocktails#i"
  post "/cocktails/i" => "cocktails#i"
  #Nested 'Cocktails#new'
  get "/cocktails/i/new" => "cocktails#new"

  resources :users

  resources :users do
    resources :cocktails, only: [:index] 
  end

  resources :cocktails, :except => [:new] do
    collection do
      get :sorted_abc
      get :sorted_zyx
    end
    resources :cocktail_ingredients, only: [:index, :new, :create, :destroy]
  end

end

app/views/layouts/_errors.html.erb
<% if object.try(:errors).try(:any?) %>
    <div id="error_explanation">
        <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
        <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li><br>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="topnav">
        <%= link_to "alcoholOK", cocktails_path %>
      </div>

    <div class="topnav_sm">
      <div style="float: right;">
        <% if logged_in? %>
          <%= form_tag("/signout", method:"delete") do %>
            <div>
              <div style="float: left;">
                <div class="name"> <%= link_to current_user.name, user_path(current_user) %> </div>
              </div>
              <div style="float: right;">
                <%= button_tag "SignOut", class: "button" %> 
                <%#link_to "Sign Out", signout_path, method: :delete %>
              </div> 
          <% end %>
        <% else %>
          <div>
            <div style="float: left;">
              <%= link_to "Sign In", signin_path %>
            </div>
            <div style="float: right;">
              <%= link_to "Sign Up", signup_path %>
             </div>
          </div>
        <% end %>
      </div>
    </div>
  
        <% if logged_in? %>
          <%= link_to "My Cocktails", user_cocktails_path(current_user)%>
          <%= link_to "New Cocktail", cocktails_i_path %>
        <% end %>
    </div>

<div>
    <div>
    <br>
      <% if flash[:message] %>
        <%= flash[:message] %>
      <% end %>
        <%= @error %>
    </div>
</div><br>

app/views/layouts/_styling.html.erb
<!DOCTYPE html>
    <html>
        <head>
            <style>
                fieldset {
                background-color: #fae3e3;
                }

                legend {
                background-color: #4e0000;
                color: white;
                padding: 5px 10px;
                }

                input {
                margin: 5px;
                }

                input[type=submit] {
                width: 20%;
                background-color: #4e0000;
                color: white;
                padding: 6px 20px;
                border: none;
                border-radius: 4px;
                }

                button {
                margin: 5px;
                }

                button[type=submit] {
                width: 20%;
                background-color: #4e0000;
                color: white;
                padding: 6px 20px;
                border: none;
                border-radius: 4px;
                }
            </style>
        </head>
    <body>
<%= yield %>
    </body></html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlcoholOK</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# javascript_pack_tag 'application', "data-turbolinks-track" => true %>
   
  </head>

  <body>

 <%= render 'layouts/navbar' %>
      
    <%= yield %>
  </body>
</html>